version: 0.0
os: linux
files:
  - source: /LibraryAPI
    destination: /var/www/LibraryAPI
hooks:
  ApplicationStop:
    - location: scripts/stop_server
      runas: root
  BeforeInstall:
    - location: scripts/install_dependencies
      runas: root
  AfterInstall:
    - location: scripts/change_configuration
      runas: root
  ApplicationStart:
    - location: scripts/start_server
      runas: root
  ValidateService:
    - location: scripts/validate_service
      runas: root